ViewModels/ManageUserRolesViewModel.cs
using BugTrackerMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerMVC.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public BTUser BTUser { get; set; }
        public MultiSelectList Roles { get; set; }
        public List<string> SelectedRoles { get; set; }
    }
}

Controllers/UserRolesController.cs
using BugTrackerMVC.Extensions;
using BugTrackerMVC.Interfaces;
using BugTrackerMVC.Models;
using BugTrackerMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTrackerMVC.Controllers
{
    [Authorize]
    public class UserRolesController : Controller
    {
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyInfoService _companyInfoService;

        public UserRolesController(IBTRolesService rolesService, IBTCompanyInfoService companyInfoService)
        {
            _rolesService = rolesService;
            _companyInfoService = companyInfoService;
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            List<ManageUserRolesViewModel> model = [];
            int companyId = User.Identity.GetCompanyId().Value;
            List<BTUser> users = await _companyInfoService.GetAllMembersAsync(companyId);

            foreach (var user in users)
            {
                ManageUserRolesViewModel viewModel = new()
                {
                    BTUser = user
                };

                var selectedRoles = await _rolesService.GetUserRolesAsync(user);
                var roles = await _rolesService.GetRolesAsync();
                viewModel.Roles = new MultiSelectList(roles, "Name", "Name", selectedRoles);

                model.Add(viewModel);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            int companyId = User.Identity.GetCompanyId().Value;
            BTUser btUser = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.BTUser.Id);
            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(btUser);
            string userRole = member.SelectedRoles.FirstOrDefault();

            if (!string.IsNullOrEmpty(userRole))
            {
                if (await _rolesService.RemoveUserFromRolesAsync(btUser, roles))
                {
                    await _rolesService.AddUserToRoleAsync(btUser, userRole);
                }
            }

            return RedirectToAction(nameof(ManageUserRoles));
        }
    }
}

Views/UserRoles/ManageUserRoles.cshtml
@using BugTrackerMVC.ViewModels
@model IEnumerable<ManageUserRolesViewModel>

<div class="row">
    <h2 class="mt-0 h3">
        Manage User Roles
    </h2>

    @foreach (var member in Model)
    {
        <div class="row">
            <div class="card col-4 m-3">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user:
                        <strong class="text-info">
                            @member.BTUser.FullName
                        </strong>
                        Use the dropdown to select the roles you want to assign to this user.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method="post">
                        <input type="hidden" asp-for="@member.BTUser.Id" />

                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="custom-label">
                                        Roles for @member.BTUser.FullName
                                    </label>
                                    <select asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple>

                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>